version: '3.7'
services:
 dynamodb-local:
   image: amazon/dynamodb-local:latest
   command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
   container_name: dynamodb-local
   ports:
    - "8000:8000"
   volumes:
    - dynamodata:/home/dynamodblocal/data

volumes:
 dynamodata:
   external: true
